### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by find-evil** [xillwillx/skiptracer#60]
When can we expect skiptracer to be ported to Python3? Thanks.

**Comment by xillwillx** [comment]
no.

**Comment by pwnhubz** [comment]
xillwillx - Its one thing to move on to things you deem more important, but your blatant lack of interest in the thousands of professionals who have come to rely on this tool (perhaps that was the real mistake) is frustrating. Maybe instead of saying that migrating to python3 on the repo landing page then saying other places just "no" is the issue.

Communicate to these people that you are or are not working on a fix for this so that someone else can pickup where you left off if needed.

I understand this is open source and not something anyone else is in a position to expect you to be responsible for, but for the sake of professionalism and consideration for others at least put out a consistent message.

**Comment by find-evil** [comment]
Even forking your code is a mistake

![FullSizeRender](https://user-images.githubusercontent.com/1427897/91568433-636d9d80-e913-11ea-9892-026d1ad4d507.jpeg)
![FullSizeRender-1](https://user-images.githubusercontent.com/1427897/91568475-65cff780-e913-11ea-8e77-37345a0a4fc7.jpeg)

**Comment by find-evil** [comment]
Harassing people on the internet for kicks but can't even keep his codebase up to date

**Comment by xillwillx** [comment]
Show me where I'm obligated to produce code on my spare time to lazy fucks with a week-old account. Try contributing to the codebase instead of crying about it.
Secondly, @find-evil / Jackie Singh can suck it too, the two-faced cunt tries to play both sides of the fence. Shouldn't even talking about codebase when you can't even run a business/keep a job/keep a marriage/keep your kids. Keep coming at me sideways for no reason and find out.
